### ISSUE TITLE
Could not find module ember-pikaday/components/pikaday-input

### ISSUE THREAD

**Issue by jdhines** [edgycircle/ember-pikaday#10]
When I build or run my Ember app with `--environment=production` then I get the above error. I just re-npm'd the package and ran the generator to be sure, and after having done that, I look in node_modules/ember-pikaday/app/components/pikaday-input.js, which does an import, supposedly from ember-pikaday/components/pikaday-input, but that file doesn't exist. There is a pikaday-input.js in ember-pikaday/addon/components however, but if I add "addon" to the path, then it won't the compile step fails when running `ember server`.

Is the import statement wrong, or am I looking in the wrong place?

Here's the entire `node_modules/ember-pikaday/app/components/pikaday-input.js`:
````
import Ember from 'ember';
import PikadayInputComponent from 'ember-pikaday/components/pikaday-input';

export default PikadayInputComponent;
````
and the file tree is:
````
ember-pikaday
|__addon
|    |__components
|         |__pikaday-input.js
|__app
     |__components
          |__pikaday-input.js
````

**Comment by jdhines** [comment]
When I do `ember g ember-pikaday` a folder called just "pikaday" is created in bower_components. There is no components folder within that. Is that part of the problem? Is the blueprint creating a folder that's not what's expected?

**Comment by stravid** [comment]
That's weird. I will take a look and report my findings!

**Comment by jdhines** [comment]
Thinking it might be the plugin, I tried switching to [ember-cli-bootstrap-datepicker](https://www.npmjs.com/package/ember-cli-bootstrap-datepicker) but that had the same problem. I can run simply `ember s` and everything works fine, just as with ember-pikaday. But when I do `ember s --environment=production` then it complains about the missing module. Strange that it's just the datepicker it can't find. I wonder if it's some ember-cli build issue, maybe tied to the fact that my datepickers are within a conditional or something. I really don't know, I'm a relative beginner at all this.

**Comment by jdhines** [comment]
Okay, looks like it had nothing to do with ember-pikaday or my other datepicker. It was due to an upstream error with Ember.Handlebars.compile being used in bootstrap-sass or something else, and when building for production, the Handlebars.runtime.js file doesn't include that function. The fix for this is described on the [ember-cli site](http://www.ember-cli.com/#customizing-a-built-in-asset). 

In essence, this could happen with any add-on, if some other one uses a non-precompiled files. So it's really an issue with whatever add-on that is.
