### ISSUE TITLE
Hard coded format string in pikaday-mixin

### ISSUE THREAD

**Issue by nomuna** [edgycircle/ember-pikaday#105]
if the pikaday component is not given any format in the template the default format is used. 

Is it possible to use the localization feature to enable setting a default format?
I mean the code snippet in README.md for *app/initializers/setup-pikaday-i18n.js*.

The issue is related to #100 I think.

Thanks,

nomuna

**Comment by duizendnegen** [comment]
See #78 and the PR that solves that problem.

**Comment by nomuna** [comment]
Thanks.
