### ISSUE TITLE
disabledWeekends doesn't work

### ISSUE THREAD

**Issue by optikalefx** [edgycircle/ember-pikaday#107]
https://cl.ly/0N3W2p1S313J

Just installed this, even tried with no other options on it.

```
{{pikaday-input
	useUTC=true
	format="MM/DD/YYYY"
	value=readyDate
	disableWeekends=true
	onSelection=(action (mut readyDate))
	minDate=minDate
	defaultDate=defaultDate
}}
```

**Comment by optikalefx** [comment]
I take that back. I see that options that are not in the readme need to go inside of the hash component.  

I would like to recommend a docs update. Either make all properties in that hash, or specify at the top that this addon ONLY implements partial feature support. For full features please use the hash options component.

**Comment by duizendnegen** [comment]
Welcoming a PR for README.md
