### ISSUE TITLE
pikaday option defaultDate & setDefaultDate not work

### ISSUE THREAD

**Issue by fogisland** [edgycircle/ember-pikaday#117]
See pikaday defaultDate example: http://jsfiddle.net/ppdJx/16/
But with this addon these two options won`t work.
I commented one line of code as below (in mixins/pikaday.js)and it works again:

``` javascript
  setPikadayDate: function() {
    const format = 'YYYY-MM-DD';
    const value = this.get('value');

    if (!value) {
      // this.get('pikaday').setDate(value, true);
    } else {
      const date = this.get('useUTC') ? moment(moment.utc(value).format(format), format).toDate() : value;

      this.get('pikaday').setDate(date, true);
    }
  },
```

**Comment by duizendnegen** [comment]
Can you share a minimal Ember Twiddle (https://ember-twiddle.com/) displaying this?
Did you set defaultDate in the option hash?

**Comment by fogisland** [comment]
I tried ember-twiddle, but some error was encountered when installing this addon in ember-twiddle.

Yes I set defaultDate in the option hash, this is my code: 
```javascript
  {{pikaday-input
  format=dateFormat
  theme="report-period-select-theme"
  readonly="readonly"
  firstDay=1
  maxDate=maxDate
  minDate=minDate
  onSelection=(action 'selectedEndDate')
  options=(hash defaultDate=endDate setDefaultDate=true)
  }}

```

I think maybe the origin code in pikaday.js prevented the underlying pikaday to set defaultDate as the initial value?

**Comment by fogisland** [comment]
BTW, this is the error I encountered in twiddle:

> ember-twiddle-7e98278….js:2 Addon ember-pikaday encountered a build error:(anonymous function) @ ember-twiddle-7e98278….js:2n @ vendor-87dd926….js:4(anonymous function) @ vendor-87dd926….js:4e.(anonymous function) @ vendor-87dd926….js:4_takeSafeStep @ vendor-87dd926….js:77_takeStep @ vendor-87dd926….js:77invoke @ vendor-87dd926….js:7flush @ vendor-87dd926….js:7flush @ vendor-87dd926….js:7end @ vendor-87dd926….js:7(anonymous function) @ vendor-87dd926….js:7
ember-twiddle-7e98278….js:2 Could not start watchman; falling back to NodeWatcher for file system events.
Visit http://ember-cli.com/user-guide/#watchman for more info.
Installed packages for tooling via npm.
installing ember-pikaday
  install bower package pikaday
  not-cached https://github.com/dbushell/Pikaday.git#*
  resolved https://github.com/dbushell/Pikaday.git#1.4.0
Installed browser packages via Bower.
  install addon ember-cli-moment-shim
Installed packages for tooling via npm.
installing ember-cli-moment-shim
Installed addon package.
Installed addon package.
Could not start watchman; falling back to NodeWatcher for file system events.
Visit http://ember-cli.com/user-guide/#watchman for more info.
DEPRECATION: EmberApp.concatFiles() is deprecated. Please use the `broccoli-concat` module directly.
DEPRECATION: EmberApp.concatFiles() is deprecated. Please use the `broccoli-concat` module directly.
headerFiles cannot contain a glob,  `[object Object]`
TypeError: headerFiles cannot contain a glob,  `[object Object]`
    at /addon-builder/node_modules/broccoli-concat/concat.js:79:13
    at Array.forEach (native)
    at ensureNoMagic (/addon-builder/node_modules/broccoli-concat/concat.js:77:16)
    at new Concat (/addon-builder/node_modules/broccoli-concat/concat.js:56:3)
    at module.exports (/addon-builder/node_modules/broccoli-concat/index.js:26:10)
    at StubApp.EmberApp.concatFiles (/addon-builder/node_modules/ember-cli/lib/broccoli/ember-app.js:368:10)
    at module.exports (/addon-builder/ember-cli-build.js:103:9)
    at CoreObject.module.exports.Task.extend.setupBroccoliBuilder (/addon-builder/node_modules/ember-cli/lib/models/builder.js:74:19)
    at CoreObject.module.exports.Task.extend.init (/addon-builder/node_modules/ember-cli/lib/models/builder.js:54:10)
    at CoreObject.superWrapper [as init] (/addon-builder/node_modules/core-object/lib/assign-properties.js:32:18)

No addon.js created(anonymous function) @ ember-twiddle-7e98278….js:2n @ vendor-87dd926….js:4(anonymous function) @ vendor-87dd926….js:4e.(anonymous function) @ vendor-87dd926….js:4_takeSafeStep @ vendor-87dd926….js:77_takeStep @ vendor-87dd926….js:77invoke @ vendor-87dd926….js:7flush @ vendor-87dd926….js:7flush @ vendor-87dd926….js:7end @ vendor-87dd926….js:7(anonymous function) @ vendor-87dd926….js:7
ember-twiddle-7e98278….js:3 Object {status_date: "2016-10-26T03:25:33.351Z", status: "build_error", addon_js: null, addon_css: null, error_log: "Could not start watchman; falling back to NodeWatc…/assign-properties.js:32:18)↵↵No addon.js created"}(anonymous function) @ ember-twiddle-7e98278….js:3n @ vendor-87dd926….js:4(anonymous function) @ vendor-87dd926….js:4e.(anonymous function) @ vendor-87dd926….js:4_takeSafeStep @ vendor-87dd926….js:77_takeStep @ vendor-87dd926….js:77invoke @ vendor-87dd926….js:7flush @ vendor-87dd926….js:7flush @ vendor-87dd926….js:7end @ vendor-87dd926….js:7(anonymous function) @ vendor-87dd926….js:7

**Comment by duizendnegen** [comment]
Yea generally speaking the support for the options hash is less thorough as properties we add natively.
The road forward here is:

* [ ] add `defaultDate` as a native argument in `pikaday-input`, e.g. `{{pikaday-input defaultDate=myDate}}`
* [ ] use `setDefaultDate` to true if `defaultDate` is supplied and pass the `defaultDate` on to `Pikaday`.

Welcoming a PR, I might not be able to get to this myself in the coming time.

**Comment by mergemeynard** [comment]
Hello. Is there any progress on this? thanks!
