### ISSUE TITLE
Glimmer and `mut` helper not working

### ISSUE THREAD

**Issue by luxferresum** [edgycircle/ember-pikaday#120]
This worked fine in ember 2.8.x, but not in 2.10.0:

    {{pikaday-input onSelection=(action (mut foo))}}
    <br>
    {{foo}}

The expected behavior is that the date can be selected and then is stored in the variable `foo` and so displayed.

When used with ember 2.10, so glimmer, the variable `foo` gets set back to `null` immediately. 

This can be reproduced on a fresh ember-cli project with `"ember-pikaday": "2.2.0",`.

**Comment by duizendnegen** [comment]
What happens in the case you use `(action 'myAction)`? Intuitively I'd say the `onSelection` action gets fired twice, but I'd have to investigate.
Would also appreciate a slimmed down Ember Twiddle showing just that.

**Comment by luxferresum** [comment]
Doesn't get fired twice. Tried that. A normal action is called as expected. 

I wasn't able to get ember-pikaday running in a twiddle at all. Can provide a git repo tho, if this would help.

**Comment by duizendnegen** [comment]
That'd surely help - when you add an observer to `foo`, does that get fired twice, or just set once (to `null`)?

**Comment by luxferresum** [comment]
[here](https://github.com/luxferresum/ember-pikaday-action-problem-demo) is a repo.
And an observer does get fired twice.

Okay, I figured out that the second `onSelection` gets fired because of [this](https://github.com/edgycircle/ember-pikaday/blob/master/addon/components/pikaday-input.js#L32) code. `Ember.isEmpty(this.$().val())` does evaluate to true, so the `this.get('onSelection')(null);` is evaluated.

So the difference is:
- When using `onSelection=(action "mutFoo")` the input already contains the date when `onPikadayClose` runs,
- and when using `onSelection=(action (mut foo)` the input is still empty.

Thats odd because a component should not see a difference!

**Comment by luxferresum** [comment]
Okay, I identified the underlaying problem.

Basically in ember `2.10` calling a `mut` helper will result in triggering `didUpdateAttrs`.
[here](https://github.com/luxferresum/ember-mut-problem) is a repo for reproduction.

However this seems fixed on `canary` and `beta`. Not sure what to do now. Wait for a hotfix?

Maybe [this](https://github.com/emberjs/ember.js/issues/14654) is related?

**Comment by duizendnegen** [comment]
Yea, if it's fixed on `canary` and `beta` I'd rather wait for a `2.10.x` bug-fix release to come out to be honest. I'll try and ping some people on the Ember.js team to see what's the schedule for that.
