### ISSUE TITLE
Interactor causes tests to repeat indefinitely

### ISSUE THREAD

**Issue by plicjo** [edgycircle/ember-pikaday#124]
When I use this line from the README:

```javascript
var interactor = openDatepicker(Ember.$('#my-datepicker'));
```

My Qunit tests repeat indefinitely.

When I use `this`, as opposed to `Ember`, my tests run just fine.

```javascript
var interactor = openDatepicker(this.$('#my-datepicker'));
```

**Comment by duizendnegen** [comment]
This could be because destroying Pikaday might not remove the picker - would you have some time to investigate?

Intuitively I'd say that `Ember.$` finds all matching elements in the entire DOM, and `this.$` doesn't - but _indefinitely_ is a bit different than I'd have expected.

**Comment by plicjo** [comment]
I wouldn't know how to begin investigating this. Thank you for your time.
