### ISSUE TITLE
Cascading issue due to is-selected class

### ISSUE THREAD

**Issue by aswinm** [edgycircle/ember-pikaday#128]
In your css, there is a class 

```
.is-selected .pika-button {
    color: #fff;
    font-weight: bold;
    background: #33aaff;
    box-shadow: inset 0 1px 3px #178fe5;
    border-radius: 3px;
}
```

Here, since the definition is very general, if there is an `is-selected` class in any of the top level containers, this class is applied to all the date elements, like this:

![image](https://cloud.githubusercontent.com/assets/4959119/22414275/2d0a08ee-e6e4-11e6-9d4c-e4015535adb1.png)

This can be fixed by making the class definition a bit more precise.

**Comment by duizendnegen** [comment]
Hi @aswinm - thanks for the report. This is actually not an issue of `ember-pikaday`, rather of `Pikaday` itself, which this library wraps.
Feel free to open an issue there.

**Comment by aswinm** [comment]
@duizendnegen Thanks.. Raised an issue in Pikaday

 https://github.com/dbushell/Pikaday/issues/635
