### ISSUE TITLE
Readonly attribute

### ISSUE THREAD

**Issue by terrancebryant** [edgycircle/ember-pikaday#129]
When using the readonly attribute `ex: {{pikaday-input readonly="readonly"}}` you can still interact with the date picker, but it seems you can also change the date.  Is this the intended functionality or should we also prevent a date from being selected?

**Comment by duizendnegen** [comment]
This is intended behavior, preventing direct changes on the input, but not the date selection itself. I must admit that `readonly="readonly"` is slightly confusing here.
