### ISSUE TITLE
change datepicker to persian datepicker

### ISSUE THREAD

**Issue by Ahmad-Sobhani** [edgycircle/ember-pikaday#135]
Hi every body.
How i can change date to date picker?? pls help me. i need it. tanx.

**Comment by duizendnegen** [comment]
Have you tried looking at Pikaday?
I am afraid I don't quite understand your question...

**Comment by Ahmad-Sobhani** [comment]
yes. i can't find persian date mode in  pikaday :(
i need a persian datepicker in emberjs but doesnt exist.

**Comment by stravid** [comment]
@Ahmad-Sobhani are you looking for localization? You can read about it in the readme: https://github.com/edgycircle/ember-pikaday#localization

**Comment by Ahmad-Sobhani** [comment]
No, I'm looking for a persian(jalali) date picker.

**Comment by duizendnegen** [comment]
Sorry, this is not the right project for doing so. I would advise either of two things:

1. try and fork the Pikaday project and adapt the year / date selection function.
2. adapt https://github.com/cibernox/ember-power-calendar, again the year / date selection function.

The biggest trouble is that sourcing the actual information is from the Javascript date-function and I am not aware of Persian / Jalali support native in JavaScript.

I'm closing this issue as there's no way to in this repository we can integrate this functionality.
