### ISSUE TITLE
minDate destructively modified

### ISSUE THREAD

**Issue by jasimon** [edgycircle/ember-pikaday#138]
Pikaday destructively modifies `minDate` and `maxDate` https://github.com/dbushell/Pikaday/blob/f638599490a7cd4144700625bef0b8463a33b06f/pikaday.js#L127

This is an issue if for things with a start and end date, where the start date is used as the min for the end date, or vice versa.  E.g.
`{{pikaday-input value=endDate minDate=startDate}}`
If you care about the start time pikaday will clear it out, and there are no changes triggered to dependent properties since pikaday is altering the underlying `Date` object.

**Comment by duizendnegen** [comment]
Welcoming a PR for this.
