### ISSUE TITLE
DEPRECATION: didUpdateAttrs | ember 2.12.0

### ISSUE THREAD

**Issue by urbany** [edgycircle/ember-pikaday#139]
Hi, ember-source@2.12.0 shows this warning:

> DEPRECATION: [DEPRECATED] Ember will stop passing arguments to component lifecycle hooks. Please change `<project@component:pikaday-input::ember3929>#didUpdateAttrs` to stop taking arguments. [deprecation id: ember-views.lifecycle-hook-arguments] See http://emberjs.com/deprecations/v2.x/#toc_arguments-in-component-lifecycle-hooks for more details.

**Comment by duizendnegen** [comment]
Welcoming a PR for this.

**Comment by duizendnegen** [comment]
Actually, this was already solved in https://github.com/edgycircle/ember-pikaday/pull/137

**Comment by urbany** [comment]
@duizendnegen great, can you release this version?

Thanks in advance!

**Comment by duizendnegen** [comment]
Working on it :)
