### ISSUE TITLE
Passing theme value

### ISSUE THREAD

**Issue by DerToti** [edgycircle/ember-pikaday#14]
Currently the newest (master) version of [Pikaday](https://github.com/dbushell/Pikaday) is supporting custom classes for the datepicker but its not provided for this component.
You also dont have the possibility to pass any option. Can you add themes as an option like this?

```
var options = {
  ...
  theme: this.get('theme')
  ...
}
```

I saw on #9 something simular was requested there.

**Comment by stravid** [comment]
Resolved with release `0.8.0`.
