### ISSUE TITLE
Pikaday conflicts with Fastclick (tap on month change closes calendar)

### ISSUE THREAD

**Issue by jdurand** [edgycircle/ember-pikaday#160]
I'm not sure where exactly this discussion should take place, but I want to share my dirty fix for other `ember-pikaday` + `ember-cli-fastclick` developers, so it doesn't feel like the wrong place.

It seems like Pikaday and Fastclick are fighting for event handlers causing an issue on touch devices where the calendar closes after taping on next-month, prev-month, year select etc.

The Fastclick way of going around this is by adding a `needsclick` class to any element on which it should avoid applying its behaviour.

In the Pikday context, more specifically the ember-pikaday context, this gets annoying. I managed to fix it doing this, but it feels very hackish:

```javascript
// app/components/form.js
import Ember from 'ember';

const { Component, $ } = Ember;

export default Component.extend({
  actions: {
    avoidFastclick() {
      $('.pika-single.needsclick button').addClass('needsclick');
    }
  }
});
```

```handlebars
{{!-- app/templates/components/form.hbs --}}
{{pikaday-input theme="my-theme needsclick"
                onOpen=(action 'avoidFastclick')
                onDraw=(action 'avoidFastclick')
}}
```

Manually adding classes to DOM elements with jQuery... I know 👎 

I'm wondering if anyone came up with something cleaner.
I'm also wondering who's to blame, Pikaday or Fastclick?

**Comment by duizendnegen** [comment]
Oof... thanks for sharing this. I'm going to close the issue as this is not something I think this plugin should support (I think this is specific per project, or if not, in the Fastclick or Pikaday library itself), but I appreciate you posting your workaround for future devs!
