### ISSUE TITLE
Accessibility ARIA support

### ISSUE THREAD

**Issue by mdcoopir** [edgycircle/ember-pikaday#170]
We are trying to make the widget accessible by adding the aria-hiddden=true attribute to the div container for the calendar.  That way the screen readers will not read the dropdown calendar, which would confuse people. It would only read the input field. Can we add this functionality to ember pikday.

Thanks,

Mark

**Comment by Ritthjp** [comment]
Yes agreed.  Needs to be accessible.

**Comment by duizendnegen** [comment]
I'm not sure this needs to take place on `ember-pikaday`, this fits best on https://github.com/dbushell/Pikaday - that one actually draws the div.
