### ISSUE TITLE
Release

### ISSUE THREAD

**Issue by scottkidder** [edgycircle/ember-pikaday#194]
It's been quite some time since a release, can we get one cut shortly?

**Comment by cah-danmonroe** [comment]
I could help as well

**Comment by AdminDev826** [comment]
Getting the warning:
`DEPRECATION: ember-cli-babel 5.x has been deprecated. Please upgrade to at least ember-cli-babel 6.6. Version 5.2.8 located: bai-ui -> ember-pikaday -> ember-cli-babel
`
"ember-pikaday": "^2.2.4"
