### ISSUE TITLE
Allow empty

### ISSUE THREAD

**Issue by onlymejosh** [edgycircle/ember-pikaday#20]
Is there a way to allow null values? If I click in the input and clear the text it doesn't set the field to null value.

**Comment by stravid** [comment]
Thanks for reporting this @onlymejosh. This sounds like a sensible default and I would have thought it already works like this. Since it obviously doesn't I will take a look and fix it :-)

**Comment by onlymejosh** [comment]
Awesome - Great to hear David :D I was surprised as well to be honest, I assumed it would work too.

**Comment by stravid** [comment]
Unfortunately Pikaday does not fire an event when this happens. The best option is to act on the `onClose` event which is triggered when the input loses focus and the datepicker is hidden. An alternative would be to use the `blur` or `change` events of the input.

What do you think is a good approach?

**Comment by onlymejosh** [comment]
I checked out  [ember-datepicker](https://github.com/SquireLabs/ember-datepicker/blob/master/addon/components/date-picker.js) and they are using the onClose event. 

I dont think thats a bad way to handle it to be honest.

**Comment by stravid** [comment]
Okay, thanks. Once I have a failing test I will push the new release!

**Comment by stravid** [comment]
I just pushed a commit to master that should fix your issue. For the the time being please use master as dependency. Once I manage to write a green test I will release a new version. But currently I'm failing to do so after running into timing brick walls for hours.

Please reopen the issue in case it is not fixed!

**Comment by onlymejosh** [comment]
Awesome David :) I’ll check this out today :D
