### ISSUE TITLE
interactor.selectDate doesn't work in IE10

### ISSUE THREAD

**Issue by jrjohnson** [edgycircle/ember-pikaday#21]
Test which pass in every other browser using selectDate fail in IE10.

**Comment by stravid** [comment]
Thanks for reporting! I will have to setup a development environment to figure out why the test helper is not working.

**Comment by jrjohnson** [comment]
Awesome, thanks.  Let me know if you need more details.

**Comment by jrjohnson** [comment]
Any thoughts on this?

**Comment by stravid** [comment]
Sorry to let you wait so long, I haven't set up a Windows development machine yet. Do you know of a way to run the tests on windows without having a windows machine?

**Comment by jrjohnson** [comment]
I use sauce labs and browser stack both have free plans for open source developers.  For one off tests browserstack is my usual choice.  I will try and dig into this as well.

**Comment by kimroen** [comment]
You can download a windows virtual machine with any version of ie preinstalled from here: http://dev.modern.ie/tools/vms/ VirtualBox is free and open source, so if you don't have vmware or Parallels you can use that.

**Comment by stravid** [comment]
@jrjohnson Thanks for reporting this in the first place, there was indeed an issue how the test helpers triggered events. @kimroen Thanks for this tip, helped me to debug it :-)

I just published `0.7.1` which should fix this issue.
