### ISSUE TITLE
Cannot clear field after selecting a date

### ISSUE THREAD

**Issue by dylanfoster** [edgycircle/ember-pikaday#24]
After clicking the pikaday input box and selecting a date, you cannot clear the field with backspace.

**Comment by stravid** [comment]
@dylanfoster can you explain your issue in more detail? When I select a date, mark the text within the input and press backspace everything is gone for me?

**Comment by dylanfoster** [comment]
@stravid I'm on 0.6.1. It looks like the onClose option was added in 0.7.0. Closing.
