### ISSUE TITLE
Placeholder attribute?

### ISSUE THREAD

**Issue by thejchap** [edgycircle/ember-pikaday#32]
Is there interest in adding the ability to pass a placeholder ?

`{{pikaday-input placeholder='Something'}}`

Can open a PR for this if yes

**Comment by polymathnyc** [comment]
I would definitely be interested in this. I was just looking into this as well.

**Comment by polymathnyc** [comment]
Ideally you would be able to pass any attribute to the input (name, data attributes, etc), as they may be needed for front-end validation.

**Comment by stravid** [comment]
There is certainly interest, feel free to work on that. There is already a pull request that is missing tests https://github.com/edgycircle/ember-pikaday/pull/19 maybe you can work from there or coordinate with the original author. If you need help with writing the appropriate tests I can help and walk you through.

I agree with @polymathnyc that it would be good to support all Pikaday attributes including certain HTML attributes. The current implementation of the supported attributes does no scale so well, I think it would be better if there was a generic way so the code base stays somewhat manageable.

**Comment by leojpod** [comment]
Hi, 

Added the tests for #19. It allows for `placholder` and `disabled` binding. 
I also placed an observer to close a Pikaday if it is open while being disabled.

**Comment by stravid** [comment]
Resolved with release `0.8.0`.
