### ISSUE TITLE
Overriding firstDay

### ISSUE THREAD

**Issue by beerlington** [edgycircle/ember-pikaday#40]
Is there a way to make Sunday the first day in the calendar? If not, would you have any interest in supporting this? I think it would just be:

```js
firstDay: this.get('firstDay') || 1, 
```
https://github.com/edgycircle/ember-pikaday/blob/master/addon/components/pikaday-input.js#L18

**Comment by beerlington** [comment]
Opened a PR for this https://github.com/edgycircle/ember-pikaday/pull/41

**Comment by evosweet** [comment]
Hi i am using the add on in my bootstrap application, but it is not allowing me  to set a year range. 

{{pikaday-input yearRange="2004,2005" value=Birthday class="form-control input-sm" format='YYYY-MM-DD' placeholder="YYYY-MM-DD" required='required' type="date"}}

**Comment by stravid** [comment]
@evosweet I tried your example code and it work's exactly as intended, what is not working for you?

Please open a new issue in the future instead of hijacking unrelated ones, thanks.

**Comment by evosweet** [comment]
My apologies,  I am new to this sort of thing. Will do Regards.
