### ISSUE TITLE
Unable  to set date range. 

### ISSUE THREAD

**Issue by evosweet** [edgycircle/ember-pikaday#42]
I would like to be able to set a dynamic date range that limits the ability of the user to selecting dates between 1915 and 18 years from the current date. 
However when I set the year  range let's say to 1915,1997 I can still select dates pass 1997 and I get no validation errors if I enter it manually.

**Comment by stravid** [comment]
This is the intended behaviour of Pikaday. The `yearRange` option does not enforce a minimum or maximum date. I explained it here: https://github.com/edgycircle/ember-pikaday/issues/36

Feel free to implement this and open up a new pull request.
