### ISSUE TITLE
Overriding event handler

### ISSUE THREAD

**Issue by thagul** [edgycircle/ember-pikaday#44]
Hi,

is it possible to override some event handlers or listen to other events? Specifically I need to validate the selected date, check if it's empty or not and then show a validation message. 
I can't observe the value because the validation message will show up also when the page is loaded for the first time. I was thinking to listen to `focus-out` or `close` events but I can't figure out how to do that.

Thanks

**Comment by stravid** [comment]
Hi @thagul!

I would create a custom component and extend the `PikadayInput` component. Within your custom component you can define your own event handlers, see the example below. `onPikadayClose` for example is triggered on `onClose` of Pikaday.

You can see the [other callbacks in the source code](https://github.com/edgycircle/ember-pikaday/blob/master/addon/components/pikaday-input.js#L16-L19).

~~~javascript
// app/components/my-input.js
import PikadayInput from 'ember-pikaday/components/pikaday-input';

export default PikadayInput.extend({
  focusOut: function() {
    console.log('focusOut');
  },
  onPikadayClose: function() {
    this._super();

    console.log('onPikadayClose');
  }
});
~~~

**Comment by a6ftcruton** [comment]
@stravid Tried extending PikadayInput as you show above and, even with nothing inside the class, I'm getting "Maximum callstack exceeded"

```
// app/components/date-picker.js
import PikadayInput from 'ember-pikaday/components/pikaday-input';

  export default PikadayInput.extend({

});

// app/templates/modals/compliance.hbs

{{date-picker value=from name="from-field" format="MM/DD/YYYY" placeholder="Date"}}

Any thoughts as to what I could be doing wrong? Also, thanks!

**Comment by stravid** [comment]
@a6ftcruton So sorry I overlooked the GitHub notification, do you still struggle with this problem?

**Comment by a6ftcruton** [comment]
@stravid This is no longer an issue for me. Thanks for this great addon :+1:
