### ISSUE TITLE
Clearing out a field doesn't update the bound variable

### ISSUE THREAD

**Issue by bluemango** [edgycircle/ember-pikaday#45]
If I bind a controller value to the date field and then clear out the date in the field the old value is never set to null.

**Comment by stravid** [comment]
Thanks for reporting this @bluemango. I will look into how we can fix this.

**Comment by rinti** [comment]
I also ran into this problem right now.

**Comment by acdx** [comment]
I have this issues as well. Also, it's not very clear from the documentation how the component deals with missing/null values.

**Comment by stravid** [comment]
@bluemango @rinti @acdx I just released `0.13.0` which fixes this issue, thanks for taking the time and reporting it!

**Comment by bluemango** [comment]
@stravid thanks! Works great.
