### ISSUE TITLE
DDAU

### ISSUE THREAD

**Issue by kmiyashiro** [edgycircle/ember-pikaday#46]
Now that Ember 1.13 is out and things are moving more towards data down, actions up, do you see moving ember-pikaday towards that paradigm instead of just two way bound attributes?

I'm having some issues dealing with the lack of granularity since I have two pikadays for custom date ranges, and then also some date range presets. When the user sets a date from pikaday, I want to set the preset to "Custom". But since all I can go off of is one of the dates changing, it's pretty hacky to detect this.

**Comment by stravid** [comment]
Thank you for opening this issue @kmiyashiro, I appreciate it when somebody thinks about improving things.

I can certainly see ember-pikaday move towards the new DDAU paradigm. While I do know what DDAU is about I have zero practical experience with it. And it seems there is still not a lot of information available.

Do you have more experience in this field? Or even better: Do you have concrete ideas how to modify ember-pikaday?

**Comment by mattmcmanus** [comment]
From a very high level, it means that components do not mutate the variables they receives. So think of anything passed in as an attribute as immutable. When one of those values change, it should fire off an event that a container component or controller is listening for. It will update the appropriate value and ember will take care of passing the right values down the component tree. 

Take a look at `ember-radio-buttons`. It does both events and mutation right now, but the event pattern works here: https://github.com/yapplabs/ember-radio-button/blob/master/addon/components/radio-button.js#L36

So for pikaday, when a user selects a data, fire off some sort of change event. 

It takes a while to grok the concept and it may feel like an awkward transition, but once the dust settles and you understand it a bit, it's a really really nice ergonomic. 

Take a look at the react docs that partially explain the idea as well: https://facebook.github.io/react/docs/interactivity-and-dynamic-uis.html

**Comment by stravid** [comment]
Thanks for your comment @mattmcmanus with these two links. I certainly understand the concept in broad strokes but lack the practical experience. Meaning I have no idea what consequences it has on application development. I will have to play around and see how it works out.

What do you think of backwards compatibility? Do you agree with me that such a paradigm switch should be a new major version?

**Comment by mattmcmanus** [comment]
Sorry if I mounded stood and gave you a lecture you didn't need!

Since ember will add angle bracket components and the ddau pattern with in
a minor release i would guess it would be a good idea keep backwards
compatibility.
On Mon, Aug 17, 2015 at 9:14 AM David Strauß <notifications@github.com>
wrote:

> Thanks for your comment @mattmcmanus <https://github.com/mattmcmanus>
> with these two links. I certainly understand the concept in broad strokes
> but lack the practical experience. Meaning I have no idea what consequences
> it has on application development. I will have to play around and see how
> it works out.
>
> What do you think of backwards compatibility? Do you agree with me that
> such a paradigm switch should be a new major version?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/edgycircle/ember-pikaday/issues/46#issuecomment-131814516>
> .
>
-- 

*Matt McManus*
Independent Developer, Designer & Technical Advocate
(215) 565-5379
http://mcmanus.io

**Comment by kmiyashiro** [comment]
I actually got to DDAU approach by using the `on*` hooks that were recently added. For example,

```js
{{pikaday-input
  value=from
  useUTC=useUTC
  format=format
  class="DateRangePicker-input js-datepicker-from"
  onPikadaySelect=selectFrom
}}
```

The `selectFrom` action lets me override the default behavior of modifying the value and letting me do whatever I want with the value in my own action.

I think the various `on*` methods should be documented so people know which ones to assign actions to.

**Comment by stravid** [comment]
I updated the README to communicate the callbacks and the state of affairs regarding DDAU. Thanks again for bringing this topic up in the first place!
