### ISSUE TITLE
Pass unrecognised options to pikaday

### ISSUE THREAD

**Issue by ismay** [edgycircle/ember-pikaday#53]
I'd like to use a couple of options from pikaday that aren't yet implemented in this addon (trigger, position). Instead of manually aliasing them, would it be an idea to pass any unrecognised options on to pikaday?

**Comment by KirillSuhodolov** [comment]
@ismay +1
I need disableWeekends option for example from list https://github.com/dbushell/Pikaday#configuration
Is any way to add them?

**Comment by stravid** [comment]
Hello @ismay and @KirillSuhodolov thanks for opening this issue. This is certainly a feature I want myself, currently I'm not sure how to handle this elegantly without doing all the work manually.

A solution I thought about is using meta programming to generate all the bindings to Pikaday.

Your idea also sounds promising, but I'm not aware how to detect unrecognised options? Can you explain this solution in more detail? Thanks a lot!

**Comment by ismay** [comment]
@stravid This is what I'm doing to move unrecognised options to another object: https://github.com/superwolff/metalsmith-layouts/blob/master/lib/index.js#L68 Don't know if that's applicable to your situation though.

**Comment by stravid** [comment]
@ismay I'm afraid that doesn't help in this situation. If I'm correct we want to give people the ability to pass any Pikaday option to the component. I'm not sure if it is possible in Ember.js to get a list of passed component parameters.

**Comment by ismay** [comment]
> I'm not sure if it is possible in Ember.js to get a list of passed component parameters.

Hmm ok, yeah you'll need that if you want to strip any addon specific parameters from what you're passing to pikaday.

**Comment by stravid** [comment]
Google sadly turns up nothing for me, I will start asking around if somebody knows a trick.

**Comment by KirillSuhodolov** [comment]
@stravid Possibly solution:
1) Give possibility to pass options hash to component

Somewhere at .js

```
options: {
 foo: 'bar',
 bar: 'foo'
}
```

at .hbs
```
{{pikaday-input value=startsAt, options=options}}
```

2) On this string merge two options hashes https://github.com/edgycircle/ember-pikaday/blob/master/addon/components/pikaday-input.js#L32

```
var pikaday = new Pikaday(Ember.merge(optionsPassedToComponent, internalOptions));
```

Thoughts?

**Comment by stravid** [comment]
@KirillSuhodolov That would certainly work, I'm not sure if I like the idea of passing an entire options hash as parameter. If we do this there will be some options as standalone parameter and than there will be others that need to be put into an options hash.

Maybe we could do a little meta programming to solve this problem elegantly..

**Comment by lan0** [comment]
:+1: for custom options

**Comment by thijsvdanker** [comment]
How about `this.attrs`?

See http://emberjs.com/blog/2015/05/10/run-up-to-two-oh.html#toc_the-code-attrs-code-property

And a working demo:
https://ember-twiddle.com/33ac989edcd605f5cced?openFiles=application.template.hbs%2Cmy-component.template.hbs

**Comment by stravid** [comment]
Thanks for the pointer @thijsvdanker, I will take a look and think about how we can use this.

**Comment by stravid** [comment]
I think the new beta version `2.0.0-beta.1` addresses this issue. Please reopen and elaborate if that's not the case, thanks!
