### ISSUE TITLE
Update to Pikaday 1.4

### ISSUE THREAD

**Issue by corrspt** [edgycircle/ember-pikaday#56]
I'd like to request an update to Pikaday 1.4 due to [these](https://github.com/dbushell/Pikaday/issues/276) [issues](https://github.com/dbushell/Pikaday/issues/303) which are solved by this [PR](https://github.com/dbushell/Pikaday/pull/389) which is only available in Pikaday 1.4

Thanks a lot.

**Comment by stravid** [comment]
Sorry for having you wait for so long @corrspt, thanks to @drapergeek this is now done.

**Comment by corrspt** [comment]
Thanks!  I should have probably done what @drapergeek did and create that PR. Many thanks @drapergeek and @stravid for the release.
