### ISSUE TITLE
Inputless Pikaday

### ISSUE THREAD

**Issue by jamesarosen** [edgycircle/ember-pikaday#58]
I have a use-case where I want to show the interactive Pikaday calendar, but not attach it to an `<input />`. That's tricky to do with the current component (mostly because it's difficult to override the `field: this.$()[0]` option).

If you think this use-case would be a good one to include in this library, I'd be happy to work on extracting the common logic to a mixin or utility class.

What do you think?

**Comment by stravid** [comment]
I think that's a great idea and users can only benefit if this addon also covers this use-case. Feel free to take a stab at how this can be accomplished.

Can I ask a question regarding your usage of `ember-pikaday`? What made you pick it / use it?

**Comment by jamesarosen** [comment]
> What made you pick it / use it?

We aren't using it yet. Our UI calls for a datepicker that doesn't have an `<input>`; it's just a calendar. I added a task to our tracker to

 1. extract the event-handling and conversion logic from the component in this library into a utility
 2. create a new component in this library based on the same utility that just has calendar selection
 3. use ember-pikaday in our app
 4. profit!!!

**Comment by jbuckner** [comment]
I'm also interested in this use case and was curious if it was actually supported and I was just missing it. I tried customizing the `tagName` and `classNames` to tried to fake it, but the click bindings started breaking (possibly related to the `this.$()[0]` field declaration).

One possible solution I was thinking of was allowing block-syntax where the contents are the clickable handle and just make the text input hidden so it could be stored, but there may be issues with that field binding.

**Comment by KeerthiHarish** [comment]
Any update on this issue?

**Comment by stravid** [comment]
Not from my side @KeerthiHarish

**Comment by stravid** [comment]
I just released `2.1.0` which adds an inputless component.
