### ISSUE TITLE
Change i18n locale after initialization

### ISSUE THREAD

**Issue by splattne** [edgycircle/ember-pikaday#59]
Is there a way to change the component's i18n localization language on the fly? In my app I set the i18n locale to the user's preference after getting that information from the store.

**Comment by tushar-chauhan** [comment]
I am also trying to get on the fly i18n working.
@splattne Did you somehow find anything helpful for this?

**Comment by splattne** [comment]
@tushar-chauhan No, since my project isn't in production yet, I'll look into this later (within the next 2-3 weeks probably). Ping me, if you have news about the matter. Thanks!

**Comment by stravid** [comment]
I did not try it myself but I doubt it works on the fly out of the box. You could extend the component with your own and set `pikaday.options` (or whatever it is called in Pikaday) in an observer based on the locale.

**Comment by evadelnuevo** [comment]
Was this functionality implemented?
