### ISSUE TITLE
Clear invalid input text

### ISSUE THREAD

**Issue by adjohnson916** [edgycircle/ember-pikaday#60]
When the input is edited manually, the plugin should optionally validate the text content, and clear it if invalid.

**Comment by stravid** [comment]
Based on what rules should the validation happen? This sounds like something highly specific per use case.

**Comment by stravid** [comment]
Please re-open once you find the time to elaborate your thoughts @adjohnson916.

**Comment by adjohnson916** [comment]
@stravid Don't we have the `format` attribute?

**Comment by albertonavarro087** [comment]
any update regarding this issue?

**Comment by stravid** [comment]
@adjohnson916 I must have overlooked your comment, sorry. `format` is indeed set it some cases.

@albertonavarro087 no update from my side, feel free to implement the feature and open a pull request to discuss it further.
