### ISSUE TITLE
Deprecation warning on Ember 1.13.x due to modifying properties in `didInsertElement` hook

### ISSUE THREAD

**Issue by iancanderson** [edgycircle/ember-pikaday#62]
See http://emberjs.com/deprecations/v1.x/#toc_modifying-a-property-within-code-didinsertelement-code

The issue is that `didInsertElement` results in `this.set()` calls, which cause rerendering and performance issues:
https://github.com/edgycircle/ember-pikaday/blob/b6440b6ec9d363669566558e059ea8b73bb7a47b/addon/components/pikaday-input.js#L11

A potential workaround is moving this code into `didRender`

**Comment by peteonrails** [comment]
This became a blocker for me in my latest project. Here is my workaround. https://github.com/edgycircle/ember-pikaday/pull/64

**Comment by stravid** [comment]
I just released `1.0.0` which includes this fix, thanks for reporting.
