### ISSUE TITLE
Ember pikaday isn't working with acceptance tests

### ISSUE THREAD

**Issue by andrehigher** [edgycircle/ember-pikaday#66]
After install it with ember-cli like: `ember install ember-pikaday`  I'm getting this error:

```Error: Could not find module `ember-pikaday/components/pikaday-input` imported from `acdc/components/pikaday-input````

So I'm assuming that pikaday is not already including their dependencies inside the project. 

I've tried to include the test helpers as well but it's still doesn't work.

**Comment by stravid** [comment]
What version of Ember CLI is used? Ember version? Do you have a repository where I can reproduce the problem?

**Comment by stravid** [comment]
Please re-open once you can provide more details, thanks!
