### ISSUE TITLE
Loosing A Day

### ISSUE THREAD

**Issue by LiquidFlame** [edgycircle/ember-pikaday#69]
I'm trying to use ember-pikaday, but I'm having issues with it not displaying the correct date. Every time the date it displays, its the previous date of the actual date. For example if the date is 04/06/2016, it displays 04/05/2016. Below is the code that I am using, I have noticed though that if I replace value with placeholder, then the date does display correctly, just not in the right format, i.e. 2016-04-06. What's going on here?

`{{pikaday-input id="effectiveDate" name="effectiveDate" class="form-control textCenter" format="MM/DD/YYYY" value=model.effectiveDate firstDay=0 disabled=isDisabledDate}}`

**Comment by stravid** [comment]
This sounds like a timezone issue. Does https://github.com/edgycircle/ember-pikaday#return-dates-in-utc-time-zone solve this issue?

**Comment by LiquidFlame** [comment]
Nope, doesn't seem to do anything. Using the following:

`{{pikaday-input id="effectiveDate" name="effectiveDate" class="form-control textCenter" format="MM/DD/YYYY" value=model.effectiveDate firstDay=0 useUTC=true disabled=isDisabledDate}}`

**Comment by stravid** [comment]
Please create an example repository where this can be reproduced and I will take a look at your problem!

**Comment by MichaelBoselowitz** [comment]
I am having a similar issue.

`{{pikaday-input value=date firstDay=0 useUTC=true format="D MMM YYYY"}}` always presents yesterday's date once selected. I am in EST -0400.

When April 13th is selected the inspector shows: `Tue Apr 12 2016 20:00:00 GMT-0400 (EDT)`. This is correct, but when displayed it should show April 13th and not April 12th.

**Comment by GRardB** [comment]
I'm running into this issue as well. The date used to format the date for the user's eyes should be in local time, but the value saved in the model should be UTC. I've worked a lot on timestamps, and may be able to help if it's unclear how to do this, but I'm pretty new to Ember-specific things.

As a "temporary" (possibly) workaround, I created a [UTC transform](https://gist.github.com/GRardB/4d3edfaec64c69c794dcfc61aa590044). This takes a serialized date from my Rails back-end (e.g. `"2016-01-22T00:00:00.000Z"`) and turns it into that same date, but in the user's timezone. When sending to the server, it transforms it back to UTC time from local time. It's a little hacky, but it seems to work just fine.

**Comment by MichaelBoselowitz** [comment]
@GRardB that's not a bad solution IMHO. I personally solve this with a computer property (on the model) which on get it transforms the model's date (in UTC) into local time and on set it simple passes through to the model's date attribute. 

Doing so allows me to deal with dates on the frontend in UTC, besides this particular edge case.

**Comment by misteroh** [comment]
Also running into this issue... The use UTC property doesn't do anything

**Comment by DanLatimer** [comment]
I'm running into this problem too. The useUTC property does make it so that the datepicker will return values to you in UTC format but if you pass a UTC formatted date to the datepicker it will assume that you want it displayed in your local timezone. useUTC should be checked when accepting dates programmatically also.

I might have time to do a PR for this but I'm not able to say for sure.

**Comment by stravid** [comment]
Thanks to @DanLatimer this is fixed with version `v2.0.0-beta.2`.
