### ISSUE TITLE
"Assertion Failed: A helper named 'pikaday-input' could not be found"

### ISSUE THREAD

**Issue by MarkMT** [edgycircle/ember-pikaday#70]
No doubt I'm missing something stupid, but I've installed ember-pikaday as described in the readme, confirmed that it's in package.json and that pikaday is in bower.json, but when I add the component to my template I get the error `Assertion Failed: A helper named 'pikaday-input' could not be found`.

As it turns out I'm not going to be able to use this anyhow - what I actually need is day-month-year html select inputs for a date-of-birth field. A calendar picker is too awkward in that application, but for the sake of future use I'm still curious what I'm doing wrong here.

**Comment by stravid** [comment]
Thanks for the issue, I will check out what goes wrong.

**Comment by stravid** [comment]
I tried but can't reproduce the problem. Please re-open if someone can provide a reproducible test repository, thanks!
