### ISSUE TITLE
DDAU hooks

### ISSUE THREAD

**Issue by misteroh** [edgycircle/ember-pikaday#72]
I'm setting `onSelect` to `(action 'dateSelected')` but it's never firing that action. When you said: ` you can extend the pikaday-input component and overwrite certain callbacks `, are you saying we should change your addon code directly?

Sorry and thanks!

Edit: Oh i got it doing `onPikadaySelect` instead. I think the docs need to be updated? I'll make a small pull request

**Comment by pixelhandler** [comment]
@misteroh I had the same issue I'll try `onPikadaySelect=(action 'dateSelected')`

**Comment by christophermlne** [comment]
@pixelhandler, @misteroh This is what I did to get DDAU working. Notice the hooks are not in the actions hash:    

```javascript```
import Ember from 'ember';
import PikadayInputComponent from 'ember-pikaday/components/pikaday-input';

const { get, run } = Ember;

export default PikadayInputComponent.extend({
  onPikadayOpen() {
    this.attrs.onOpen();
  },
  onPikadayClose() {
    this.attrs.onClose();
  },
  onPikadayRedraw() {
    const pikaday = get(this, 'pikaday', pikaday);

    run.later(() => {
      return pikaday.adjustPosition();
    });
  }
});
```
```
{{modify-ember-pickaday
  firstDay=0
  value=startDate
  placeholder='Date'
  class='form-control'
  format="MM/DD/YYYY"
  yearRange="currentYear,2010"
  onOpen=(action 'myFunc1')
  onClose=(action 'myFunc2')
}}
```

**Comment by stravid** [comment]
I think the new beta version `2.0.0-beta.1` addresses this issue. Please reopen and elaborate if that's not the case, thanks!
