### ISSUE TITLE
Title and hidden attributes

### ISSUE THREAD

**Issue by ykaragol** [edgycircle/ember-pikaday#76]
According to the W3 standards, `title `and `hidden `attributes are [global attributes](https://www.w3.org/TR/html-markup/global-attributes.html). So these two should be considered to be added to the `attributebindings`.

**Comment by stravid** [comment]
@ykaragol can you please elaborate your problem / idea further? Currently I don't understand what you are trying to tell me :)

**Comment by ykaragol** [comment]
I've updated my comment and sent a pull request.
