### ISSUE TITLE
months on the i18n object is undefined

### ISSUE THREAD

**Issue by lmcardle** [edgycircle/ember-pikaday#78]
I am trying this addon out in an existing project, however I am getting the error: "Cannot read property '0' of undefined". The resulting line of code causing this issue is here: https://github.com/dbushell/Pikaday/blob/master/pikaday.js#L364. Has anyone come across this before?

**Comment by ynnoj** [comment]
@lmcardle Yep, encountering same issue here 😞

**Comment by marcocampos** [comment]
@lmcardle Same here.

**Comment by ynnoj** [comment]
I tried a fork that updated the `pikaday` dependency from `1.4.0` to follow the master branch, as the last release is a way behind.

No such luck :(

**Comment by stravid** [comment]
I just tried to reproduce this problem but failed, blank Ember CLI project newest `ember-pikaday`.
Can anyone of you please create a repository were the problem is reproducible?

Basically it seems that not all I18n keys are set, but I can only tell for sure if I see the error happen.

**Comment by stravid** [comment]
Please re-open in case you have an update for me @ynnoj @marcocampos @lmcardle  :)

**Comment by marcocampos** [comment]
Wrong Campos, mate :)

**Comment by ynnoj** [comment]
@stravid I was unable to replicate the issue on a new ember-cli project. However, I've just come back to work on the branch of the project I was having issues on and I've managed to track the problem down to the use of `ember-i18n`.

I have an `initializer` which injects the `i18n` service into all the projects components. Removing the `initializer` restores functionality.

**Comment by lcpriest** [comment]
@stravid 

The issue is with ember-i18n and ember-pikaday. When ember-i18n is used with an initializer (https://github.com/jamesarosen/ember-i18n/wiki/Doc:-i18n-Service), it is passed through in the pikaday mixin https://github.com/edgycircle/ember-pikaday/blob/cad86f3fa6e52bee32064bc482745723802d38bd/addon/mixins/pikaday.js#L17, which overrides the defaults set by this addon.

The issue then stems from the fact that ember-i18n uses `i18n.t('months')` to get months, rather than be located directly on the service itself (ember-pikaday calls `i18n.months`.

**Comment by lcpriest** [comment]
I have a working fork here: https://github.com/advocately/ember-pikaday-ember-i18n

It's not mergeable as it drops support for other i18n libraries, but it explains the issue I am describing pretty clearly.

**Comment by duizendnegen** [comment]
@lcpriest would something in following lines work:

```javascript
// line 16
if (isPresent(this.get('i18n'))) {
  if(isPresent(this.get('i18n').t)) {
    options.i18n = { previousMonth: this.get('i18n').t('previousMonth').toString(), /* etc. */ };
  } else {
    options.i18n = this.get('i18n');
  }
}
```

I'd like to get `ember-pikaday` up to date with the latest version of `ember-i18n`, but I agree we can't drop support for other i18n libs - we could check what library we're dealing with, only then using the `t` translation helper.

**Comment by lcpriest** [comment]
@duizendnegen yeah, that should work great.

This is the line in question by the way:
https://github.com/advocately/ember-pikaday-ember-i18n/blob/master/addon/mixins/pikaday.js#L18

**Comment by duizendnegen** [comment]
My `ember-i18n` knowledge isn't that great, so could I ask why `.string` should be used?
Would you mind updating your library with the solution mentioned above, then opening a PR?

**Comment by lcpriest** [comment]
```
this.get('i18n').t('months').toString()
"January,February,March,April,May,June,July,August,September,October,November,December"
this.get('i18n').t('months')
SafeString {string: "January,February,March,April,May,June,July,August,September,October,November,December"}
```

Working on it now :)

**Comment by duizendnegen** [comment]
🎉
