### ISSUE TITLE
Test helpers - error with touch event

### ISSUE THREAD

**Issue by mciastek** [edgycircle/ember-pikaday#79]
Hi,

I used test helpers for ember-pikaday in my tests using Phantom.js and it throws: `TypeError: undefined is not an object (evaluating 'event.changedTouches.length')`. I think it's caused by that [line](https://github.com/edgycircle/ember-pikaday/blob/master/addon/helpers/pikaday.js#L18):

```js
var selectEvent = 'ontouchend' in document ? 'touchend' : 'mousedown';
```

Maybe it should be change to `tap` event?

Regards

**Comment by stravid** [comment]
Thanks for reporting @mciastek this issue. Can you create a repository where I can reproduce the problem? Thank you in advance :)

**Comment by stravid** [comment]
Please re-open in case you have an update for me @mciastek :)
