### ISSUE TITLE
DDAU doesn't support clearing input

### ISSUE THREAD

**Issue by DanLatimer** [edgycircle/ember-pikaday#81]
clearing input is supported via 2 way data binding as seen here: https://github.com/edgycircle/ember-pikaday/commit/7293b7795258154058d7653ee6019281d61b18e6

```javascript
onPikadayClose: function() {
  if (this.get('pikaday').getDate() === null || Ember.isEmpty(this.$().val())) {
    this.set('value', null);
  }
},
```

But we aren't sending a onSelectionChanged() event in that case. To get DDAU to work with clearing input events we would want to do something like:
```javascript
onPikadayClose: function() {
  if (this.get('pikaday').getDate() === null || Ember.isEmpty(this.$().val())) {
    this.set('value', null);
    this.get('onSelection')(null);
  }
},
```

**Comment by stravid** [comment]
@DanLatimer good catch, thanks for the issue! Do you have time to create a pull request fixing this and adding a regression test case?
