### ISSUE TITLE
stylesheet no longer loads after upgrade to ember-cli 2.6.1

### ISSUE THREAD

**Issue by dougmcclurg** [edgycircle/ember-pikaday#82]
After upgrading our app from `ember-cli : 1.13.8` to `ember-cli : 2.6.1` we lost any vendor styles we were getting from pikaday.

We are on ` ember-pikaday : 1.1.0`, `ember-cli : 2.6.1` and `ember : 2.4.3`

I have tried adding the line in ember-cli-build to import the css from pikaday   `app.import('bower_components/pikaday/css/pikaday.css');` with no success. 

In order to get this working i've had to do the following `@import 'bower_components/pikaday/css/pikaday';` into my app.scss

I have also tried upgrading to beta ember-pikaday with no success.

Wondering if this is a known issue or if anyone can help with resolution.

**Comment by stravid** [comment]
Thanks for the report @dougmcclurg, would you mind creating a test repository where this happens so I can investigate?

**Comment by stravid** [comment]
Please re-open in case you have an update for me @dougmcclurg :)
