### ISSUE TITLE
stopPropagation for click event

### ISSUE THREAD

**Issue by Nuzsk** [edgycircle/ember-pikaday#85]
Ver: v2.0.0-beta.1

"ember-pikaday" component does  action of parent block when input field was clicked.
Example error:
```
<a id="dayPickerTrigger" {{action 'openDayPicker'}}>
    Day {{pikaday-input  onSelection=(action 'setDateLimitation' 'day')}}
</a>
```
Fix:
```
import PikadayInputComponent from 'ember-pikaday/components/pikaday-input';
export default PikadayInputComponent.extend({
  click(e)
  {
    e.stopPropagation();
  }
});
```

**Comment by stravid** [comment]
What is your use case? Please elaborate, stopping event propagation without a clear reason sounds wrong and broken to me.

**Comment by Nuzsk** [comment]
@stravid This is necessary as an alternative to "trigger" pikaday option that works exclusively with the dom element. In this case, I want to programmatically open and close the datepicker by clicking on the parent dom element. If it does not apply stopPropagation - there recursion.

example:
```
export default Ember.Component.extend({
  actions: {
    dayPickerValueChange(value)
    {
        //...
    },
    openDayPicker()
    {
      this
        .children('input')
        .click();
    }
  }
});
```
```
<!--...component template -->
<a  {{action 'openDayPicker'}}>
    Day {{pikaday-input  onSelection=(action 'dayPickerValueChange')}}
</a>
<!--...component template -->
```

**Comment by stravid** [comment]
In your use case, wouldn't be the solution to not nest the input inside your trigger? I so reluctant to your idea of using `stopPropagation` because I have no idea what the consequences would be.

**Comment by stravid** [comment]
Please re-open in case you want to discuss this further.

**Comment by bttf** [comment]
We're experiencing this as a pain point when we try to open the pikaday input by using the `click()` event. After `click()` fires, pikaday will not only open but fire the `onSelection` event w/ `null`, causing our dependent computed properties to break. We need to be able to click the pikaday to open it w/out onSelection firing at the same time
