### ISSUE TITLE
Is the `value` 2-way binding still working on 2.X?

### ISSUE THREAD

**Issue by hdra** [edgycircle/ember-pikaday#89]
Title question. I recently upgraded to `2.0.0` so that I'm able to clear the selected value, but I noticed that although I'm able to set the initial selected date, changing the date via Pikaday afterward doesn't change the bound value. 

It is able to set the bound value to `null` when I clear the input though.

Is this an intended deprecation or is it a bug?

**Comment by splattne** [comment]
I think you can do it this way:

    {{pikaday-input value=someDate onSelection=(action (mut someDate)) ... }}

**Comment by stravid** [comment]
2.X tries to follow Embers lead when it comes to Data Down - Actions Up. In this case it means the component can't change bounded values. You have to do it in your own action. (See @splattne answer for a shortcut.)

Clearing the input and setting the bound value to `null` seems like a bug. I'm currently swamped at work and will try to take a look as fast as possible.

**Comment by stravid** [comment]
Please re-open in case you have further questions.

**Comment by jeffrey008** [comment]
@splattne Thanks for your solution. It works for me, but I am quite confused about what's happening there. AFAIK, `value=someDate` will set the default value of pikaday to `someDay`. When user selected a day,  `mut someDate` will allow pikaday to modify `someDay` defined in the Controller.  But how does it know what value should it change to? 

Also I tried 
`{{pikaday-input value=someDate onSelection=(action (mut someDate) value=target.value) ... }}`
but this doesn't work. I don't know why.
