### ISSUE TITLE
Configuring Pikaday?

### ISSUE THREAD

**Issue by lolmaus** [edgycircle/ember-pikaday#9]
Is it possible to pass configuration options to Pikaday?

It's important that the widget updates when properties passed as options change dynamically.

**Comment by stravid** [comment]
This is currently not possible apart from the `format` option. I will happily accept a pull request implementing this feature.

**Comment by lolmaus** [comment]
Sorry, i'm currently using vanilla bootstrap-datepicker. Its built-in date ranges feature saves me a lot of typing.

bootstrap-datepicker does not allow live-updating some configuration options, so i have to do `this.rerender()` on my component wrapper. :(

I wonder whether Pikaday is better in this concern.

**Comment by stravid** [comment]
Good question, I never had a use case of live-updating configuration options so I can't tell you if Pikaday is better suited in this regard.
